---

services:

  duckdns:

    image: lscr.io/linuxserver/duckdns:latest

    container_name: duckdns

    network_mode: host #optional

    environment:

      - PUID=1000 #optional

      - PGID=1000 #optional

      - TZ=Asia/Ho_Chi_Minh #optional

      - SUBDOMAINS=kienletv-wg2.duckdns.org

      - TOKEN=66fdf909-6b03-47f4-a772-02146bd97ff0

      - UPDATE_IP=ipv4 #optional

      - LOG_FILE=false #optional

    volumes:

      - ./duckdns/config:/config #optional

    restart: unless-stopped
